export const ERRORS = {
    PAUSED: 'Paused',
    NOT_GOVERNANCE: "NotGovernance",
    KEYPRICE_TOOLOW_CANNOT_FRAGMENT: "KeyPriceTooLowCanNotBeFragment",
    FUNDS_NOT_ENOUGH: "FundsNotEnough",
    LARGE_THAN_MAX_ACCEPTPRICE: "LargeThanMaxAcceptPrice",
    LESS_THAN_MIN_ACCEPTPRICE: "LessThanMinAcceptPrice",
    FRAGMENT_POOL_NOT_EXIST: "FragmentPoolNotExist",
    NOT_TOMO_FRAGMENT_ENTRYPOINT: "NotTomoFragmentEntryPoint",
    LIQUIDITY_NOT_ENOUGH: "LiquidityNotEnough",
    LIQUIDITY_PROVIDER_CANNOT_BUY: "LiquidityProviderCanNotBuy",
    CANNOT_BUY_EXCEED_FRAGMENTPARAM: "CanNotBuyExceedFragmentParam",
    LIQUIDITY_PROVIDER_CANNOT_SELL: "LiquidityProviderCanNotSell",
    NOT_ENOUGH_FRAGMENT: "NotEnoughFragment",
    ETH_LIQUIDITY_NOT_ENOUGH: "ETHLiquidityNotEnough",
    CALLER_NEEDBE_FRAGMENTPOOL: "CallerNeedBeFragmentPool",
    NOT_LOCK_OWNER: "NotLockOwner",
    CANNOT_SELL_BEFORE_DEADLINE: "CanNotSellBeforeDeadline",
    VOTEPASS_NOT_ENOUGH: "VotePassNotEnough",
    NOT_AVAIABLE_AMOUNT: "NotAvaiableAmount",
    CANNOT_TRANSFER_SELF: "CanNotTransferSelf",
    JUST_LIQUIDITYPROVIDER_CAN_QUIT: "JustLiquidityProviderCanQuit",
    DEADLINE_NEED_LARGETHAN_ONEWEEK: "DeadLineNeedMoreThanOneWeek",
    MSGVALUE_CANNOTBE_ZERO: "MsgValueCanNotBeZero",
    ETH_VALUE_TOO_LOW: "ETHValueTooLow",
  };
  